typography_spectrum: 0.621786
color:
  saturation: 0.3926612
  lightness: 0.5634359
  brandStrength: 0.7937379
  brandColors:
    - '#102C44'
    - '#BD964B'
    - '#D1BF96'
    - '#464F45'
    - '#EBDBC3'
  rhythmicContrast: 0.2953838
layout_spectrum: 0.6723571
name: Scotavius
title: Scotavius
description: to smell one is to know one
